### PR TITLE
Fixed bugs and start to declupling UI component

### LINKED ISSUE #1: Bug with the material version 1.1.2-rc2
**Describe the bug**
The behavior it is not correct

**To Reproduce**
1 Run the demo login

**Expected behavior**
Correct foreground color in the password component

**Screenshots**
Selection_033

### PR DESCRIPTION
**Pull request by vincenzopalazzo**

### CODE REVIEW

File: src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java [hunk 1]
```diff
@@ -35,7 +36,8 @@
       UIManager.put("TextFieldPlaceholder.inactiveBackground", MaterialColors.BLACK);
       UIManager.put("TextFieldPlaceholder.selectionBackground", MaterialColors.LIGHT_BLUE_400);
       UIManager.put("TextFieldPlaceholder.selectionForeground", MaterialColors.BLACK);*/
-      UIManager.put("TextFieldPlaceholder.placeholderColor", MaterialColors.RED_800);
+      UIManager.put("Placeholder.foreground", MaterialColors.COSMO_DARK_GRAY);
```
Comment (vincenzopalazzo) [inline src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java:39]: @zanderson9 to set the color of the placeholder, foreground and background are supported.

File: src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java [hunk 2]
```diff
@@ -63,15 +65,24 @@ public void initComponent() {
     Icon icon =
         MaterialImageFactory.getInstance()
             .getImage(MaterialIconFont.LOCATION_SEARCHING, 16, MaterialColors.COSMO_DARK_GRAY);
+    Icon menu =
+        MaterialImageFactory.getInstance()
+            .getImage(MaterialIconFont.MORE_VERT, 22, MaterialColors.COSMO_DARK_GRAY);
     JTextField textField = new JTextField();
     textField.setPreferredSize(new Dimension(100, 20));
-    textFieldPlaceholder = new JMarsSearch(textField, icon);
+    textFieldPlaceholder = new JMarsSearch(textField, icon, menu);
```
Comment (vincenzopalazzo) [inline src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java:73]: @zanderson9 The icon of the menu button is passed in the constructor

File: src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java [hunk 3]
```diff
@@ -63,15 +65,24 @@ public void initComponent() {
...
     icon =
         MaterialImageFactory.getInstance()
             .getImage(MaterialIconFont.SEARCH, 20, MaterialColors.COSMO_DARK_GRAY);
     textFieldPlaceholder
+        .addMenuActions(
```
Comment (vincenzopalazzo) [inline src/test/java/io/vincenzopalazzo/placeholder/DemoFrame.java:78]: @zanderson9 To add the action in the button.

Alert! The order of the call is important!

**Review by vincenzopalazzo — COMMENTED** [review]
Hi @zanderson9,

In the review below are summarized all the changess that you need to know instant to fix the bug in JMars.

The change include the following bug fixing

- [X] Menu button in the JMars example
- [X] unable to change place holder color.
